<?php
require("../../class/connect.php");
if(!defined('InEmpireCMS'))
{
	exit();
}
$myuserid=(int)getcvar('mluserid');
$mhavelogin=0;
if($myuserid)
{
	include("../../class/db_sql.php");
	include("../../class/user.php");
	include("../../data/dbcache/MemberLevel.php");
	$link=db_connect();
	$empire=new mysqlquery();
	$mhavelogin=1;
	//数据
	$myusername=RepPostVar(getcvar('mlusername'));
	$myrnd=RepPostVar(getcvar('mlrnd'));
	$r=$empire->fetch1("select ".$user_userid.",".$user_username.",".$user_group.",".$user_userfen.",".$user_money.",".$user_userdate.",".$user_havemsg.",".$user_checked." from ".$user_tablename." where ".$user_userid."='$myuserid' and ".$user_rnd."='$myrnd' limit 1");
	if(empty($r[$user_userid])||$r[$user_checked]==0)
	{
		EmptyEcmsCookie();
		$mhavelogin=0;
	}
	//会员等级
	if(empty($r[$user_group]))
	{$groupid=$user_groupid;}
	else
	{$groupid=$r[$user_group];}
	$groupname=$level_r[$groupid]['groupname'];
	//点数
	$userfen=$r[$user_userfen];
	//余额
	$money=$r[$user_money];
	//天数
	$userdate=0;
	if($r[$user_userdate])
	{
		$userdate=$r[$user_userdate]-time();
		if($userdate<=0)
		{$userdate=0;}
		else
		{$userdate=round($userdate/(24*3600));}
	}
	//是否有短信息
	$havemsg="";
	if($r[$user_havemsg])
	{
		$havemsg="<a href='".$public_r['newsurl']."e/member/msg/' target=_blank><font color=red>您有新信息</font></a>";
	}
	//$myusername=$r[$user_username];
	db_close();
	$empire=null;
}
if($mhavelogin==1)
{
?>
document.write("<div class=\"log\">	<span>		<font color=red><b><?=$myusername?></b></font>&nbsp;&nbsp;<?=$havemsg?>		<img src=\"/skin/default/images/hw_000470.gif\" />	</span>	<span>		<a href=\"/e/member/cp/\" target=\"_parent\">会员中心</a>		<img src=\"/skin/default/images/hw_000470.gif\" />	</span>	<span>		<a href=\"/e/enews/?enews=exit&ecmsfrom=9\" onclick=\"return confirm(\'确认要退出?\');\">退出</a>					</span>	</div><div class=\"search\" id=\"search_1\"> 	<form action=\'/e/sch/index.php\' method=\"GET\" name=\"search_news\" id=\"search_news\">		<input name=\"keyboard\" type=\"text\" id=\"search-box-h\" class=\"text\"/>        <input type=\"hidden\" name=\"field\" value=\"1\"/>        <input type=\"submit\" id=\"searchButton\" name=\"Submit22\" value=\"\" />	</form></div>");
<?
}
else
{
?>
document.write("<div class=\"log\">	<span>		<a href=\"/e/member/login/\" >登录</a>		<img src=\"/skin/default/images/hw_000470.gif\" />	</span>	<span>								<a href=\"/e/member/register/\">注册</a>		</span>	</div><div class=\"search\" id=\"search_1\"> 	<form action=\'/e/sch/index.php\' method=\"GET\" name=\"search_news\" id=\"search_news\">		<input name=\"keyboard\" type=\"text\" id=\"search-box-h\" class=\"text\"/>        <input type=\"hidden\" name=\"field\" value=\"1\"/>        <input type=\"submit\" id=\"searchButton\" name=\"Submit22\" value=\"\" />	</form></div>");
<?
}
?>